protected/models/Program.php
<?php
/**
 * Модель для таблицы "data_Program".
 *
 * Поля:
 * @property integer $id
 * @property string $title
 * @property string $image
 * @property string $lang
 * @property integer $parent_ProgramCategory_id
 * @property integer $age
 * @property integer $time
 * @property integer $created_at
 * @property integer $status
 *
 * Связи:
 * @property ProgramCategory $parentProgramCategory
 */
class Program extends CActiveRecord
{
	/**
	 * @return Program the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	/**
	 * @return string title of model
	 */
	public static function modelTitle()
	{
		return 'Твпрограммы';
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'data_Program';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			array('title, image, lang, age, time, created_at, status', 'required'),
			array('parent_ProgramCategory_id, age, time, created_at, status', 'numerical', 'integerOnly'=>true),
			array('title, image', 'length', 'max'=>255),
			array('lang', 'length', 'max'=>10),
			array('image', 'file', 'on'=>'upload'),
			array('id, title, image, lang, parent_ProgramCategory_id, age, time, created_at, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			//'parentProgramCategory' => array(self::BELONGS_TO, 'ProgramCategory', 'parent_ProgramCategory_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Название',
			'image' => 'Изображение',
			'lang' => 'Lang',
			'parent_ProgramCategory_id' => 'Категория',
			'age' => 'Age',
			'time' => 'Time',
			'created_at' => 'Дата создания',
			'status' => 'Видимость',
		);
	}

	/**
	 *
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;
		$criteria->compare('id',$this->id,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('lang',$this->lang,true);
		$criteria->compare('parent_ProgramCategory_id',$this->parent_ProgramCategory_id,true);
		$criteria->compare('age',$this->age);
		$criteria->compare('time',$this->time,true);
		$criteria->compare('status',$this->status,true);
        $pagination = array('pageSize'=> 30);
        return new CActiveDataProvider($this,array(
            'criteria'   => $criteria,
            'pagination' => $pagination
        ));
	}
    
    public function beforeValidate() {
	if ($this->created_at==0) {
		$this->created_at=time();	
	}
	if (strstr($this->created_at,'-')) {
            $date=explode('-',$this->created_at);
            $minute = $hour = 0;
            if(isset($_POST['_time']['created_at'])){
                $time = explode(':',$_POST['_time']['created_at']);
                $hour = (int)$time[0];
                $minute = (int)$time[1];
            }
            $this->created_at=mktime( $hour, $minute, 0, $date[1], $date[0], $date[2] );
	}
	if (strstr($this->time,'-')) {
        $date=explode('-',$this->time);
        $minute = $hour = 0;
        if(isset($_POST['_time']['time'])){
            $time = explode(':',$_POST['_time']['time']);
            $hour = (int)$time[0];
            $minute = (int)$time[1];
        }
        $this->time=mktime( $hour, $minute, 0, $date[1], $date[0], $date[2] );
	}
        return true;
    }
    
    public function getLangList()
    {
    	return array(
    		"ru", "kz", "en"
    	);
    }

    public function getLangTitle($lang="")
    {
    	if($lang===""){
    		$lang = $this->lang;
    	}
    	return Yii::app()->system->getLangTitle($lang);
    }

    public function getCategoryList(){
    	return array(
    		"музыка",
    		"кино",
    		"искусство",
    	);
    }

    public function defaultScope() {
        return array(
            'order' => 'created_at DESC',
        );
    }

    public function getPreview($type,$key=0){
    	$images = json_decode($this->image,true);
    	if($images){
	    	if(array_key_exists($key, $images)){
	    		$key = 0;
	    	}
	    	$file = "upload/".__CLASS__."/".$type."/".$images[$key];
	    	if(is_file($file)){
	    	}
	    		return CHtml::image("/".$file,$this->title);
    	}
    	return null;
    }
        
    /**
	 * @return array of model options
	 */     
	public function options()
	{
        return array(
            'image' => array(
                'full' => array(
                    'width' => 600,
                    'height' => 600,
                    'type' => 'resize'
                ),

                'list' => array(
                    'width' => 65,
                    'height' => 39,
                    'type' => 'crop'
                ),

                'sm' => array(
                    'width' => 50,
                    'height' => 50,
                    'type' => 'crop'
                ),
            
                'tm' => array(
                    'width' => 160,
                    'height' => 120,
                    'type' => 'crop'
                ),

            )
        );
	}
    
}

protected/controllers/FileController.php
<?php

class FileController extends Controller {
	const UPLOAD_PATH = 'upload';
	private $_imageTypes = array('image/png','image/jpeg');

	public function actionResize($url="http://xupload.sergey/img-content/homyak.jpg",$size="100x100",$type="crop")
	{
		$ch = curl_init();      
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);   
		curl_setopt($ch, CURLOPT_URL, $url);     
		$result = curl_exec($ch);   
		$http_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		if($http_status=="200"){
			$imageSize = getimagesize($url);
			$pathinfo = pathinfo($url);
			if(in_array($imageSize['mime'], $this->imageTypes)){
				$tmpDir = "upload/tmp";
				$filename = md5_file($url).".".$pathinfo['extension'];
				$filePath = $tmpDir."/".$filename;

				if(!is_dir($tmpDir)){
					mkdir($tmpDir, 0777, true);
				}
				copy($url, $filePath);
				Yii::import('ext.image.*');
				$image = new Image($filePath);
				if($image){
					$sizes = explode("x", $size);
					$width = $sizes[0];
					$height = $sizes[1];
					$image = FileHelper::resizeImage($image,$width,$height,$type)
					//$image->crop(200,200)
					// ->filter("velvet")
					// ->filter("chrome")
					// ->filter("lift")
					// ->filter("canvas")
					// ->filter("vintage")
					// ->filter("monopin")
					// ->filter("antique")
					->filter("blackwhite")
					// ->filter("boost")
					// ->filter("sepia")
					->filter("blur")
					->render();
					// $image->render();
					// $filter = new FilterGd;
					// var_dump($filter->gd_filter_image($url,'monopin'));
					//$image->render();
					//$image->save($tmpDir."/".$size.".".$image->image->extension);
				}

			}else{
				throw new CHttpException(500,"Не верный тип файла");
			}
			// $UPimage = new CUploadedFile( $path['basename'], $name, $type, filesize( $name ), 0 );
			// header('Pragma: public');
   //          header('Expires: 0');
   //          header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
   //          header('Content-Transfer-Encoding: binary');
   //          header("Content-type: image/png");
            //header('Content-Length ' . filesize($result));
            //echo $result;
			
		}else{
			throw new CHttpException(500,"Файл не найден");
		}
		curl_close($ch);
	}

	public function getImageTypes(){
		return $this->_imageTypes;
	}

}

protected/controllers/SiteController.php
<?php
Yii::import("xupload.models.XUploadForm");
class SiteController extends Controller {

	public function actions() {
		return array(
			'upload' => array('class' => 'xupload.actions.XUploadAction', 
				'path' => dirname(Yii::app() -> getBasePath()) . "/upload", 
				"publicPath" => Yii::app()->getBaseUrl()."/upload",
			), 
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex() {
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		//$model = new XUploadForm;
		$model = Program::model()->findByPk(1);
		// $model = new Program;
		$this -> render('index', array('model' => $model, ));
	}

	public function actionFile() {
		$this -> render('file', array('model' => $model, ));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError() {
		if ($error = Yii::app() -> errorHandler -> error) {
			if (Yii::app() -> request -> isAjaxRequest)
				echo $error['message'];
			else
				$this -> render('error', $error);
		}
	}

}

protected/views/layouts/main.php
<!DOCTYPE HTML>
<!--
/*
 * jQuery File Upload Plugin Demo 6.5.1
 * https://github.com/blueimp/jQuery-File-Upload
 *
 * Copyright 2010, Sebastian Tschan
 * https://blueimp.net
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/MIT
 */
-->
<html lang="en">
<head>
<meta charset="utf-8">
<title>jQuery File Upload Demo</title>
<meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bar and preview images for jQuery. Supports cross-domain, chunked and resumable file uploads. Works with any server-side platform (Google App Engine, PHP, Python, Ruby on Rails, Java, etc.) that supports standard HTML form file uploads.">
<meta name="viewport" content="width=device-width">
<!-- Bootstrap CSS Toolkit styles -->
<link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap.min.css">
<!-- Generic page styles -->
<link rel="stylesheet" href="<?php echo Yii::app()->baseUrl; ?>/css/style.css">
<!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
<link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap-responsive.min.css">
<!-- Bootstrap CSS fixes for IE6 -->
<!--[if lt IE 7]><link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap-ie6.min.css"><![endif]-->
<!-- Bootstrap Image Gallery styles -->
<link rel="stylesheet" href="http://blueimp.github.com/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css">
<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="https://github.com/blueimp/jQuery-File-Upload">jQuery File Upload</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo Yii::app()->createUrl("site/index"); ?>">Demo</a></li>
                    <li><a href="http://www.yiiframework.com/extension/xupload/">Downloads</a></li>
                    <li><a href="https://github.com/Asgaroth/xupload">Source Code</a></li>
                    <li><a href="https://github.com/blueimp/jQuery-File-Upload/wiki">Documentation</a></li>
                    <li><a href="https://github.com/Asgaroth/xupload/issues">Issues</a></li>
                </ul>
                <div class="pull-right">
                	<ul class="nav">
	                    <li><a href="http://twitter.com/#!/asgarothbelem">@AsgarothBelem</a></li>
                	</ul>	
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <?php echo $content; ?>
</div>
<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn modal-download" target="_blank">
            <i class="icon-download"></i>
            <span>Download</span>
        </a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
            <i class="icon-play icon-white"></i>
            <span>Slideshow</span>
        </a>
        <a class="btn btn-info modal-prev">
            <i class="icon-arrow-left icon-white"></i>
            <span>Previous</span>
        </a>
        <a class="btn btn-primary modal-next">
            <span>Next</span>
            <i class="icon-arrow-right icon-white"></i>
        </a>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="http://blueimp.github.com/JavaScript-Templates/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="http://blueimp.github.com/JavaScript-Canvas-to-Blob/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS and Bootstrap Image Gallery are not required, but included for the demo -->
<script src="http://blueimp.github.com/cdn/js/bootstrap.min.js"></script>
<script src="http://blueimp.github.com/Bootstrap-Image-Gallery/js/bootstrap-image-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]><script src="<?php echo Yii::app()->baseUrl; ?>/js/cors/jquery.xdr-transport.js"></script><![endif]-->
</body> 
</html>

protected/views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/file.php
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableAjaxValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
));
echo CHtml::hiddenField('Program_page',$_GET['Program_page']);
?>
    <div class="form-actions">
        <button class="btn btn-success" type="submit">
            <?=$model->isNewRecord ? 'Добавить' : 'Сохранить'; ?>
        </button>
        <span class="text_button_padding">или</span>        
    	<?=CHtml::link('назад', array('list','Program_page'=>$_GET['Program_page'])); ?>    </div>
    	<?php echo $form->textField($model, 'title', array('size' => 60, 'maxlength' => 255, 'class'=>'span12')); ?>
		<?php echo $form->fileField($model, 'image',array('class'=>'input-file'));; ?>
        <?php echo $form->dropdownList($model, 'lang',$model->langList, array('class'=>'span4')); ?>
		<?php echo $form->dropdownList($model, 'parent_ProgramCategory_id',$model->categoryList, array('class'=>'span4')); ?>
		<?php echo $form->textField($model, 'age',array('class'=>'span12')); ?>
		<?php echo $form->dateField($model, 'created_at',array('class'=>'span'));; ?>
		<?php echo $form->checkBox($model, 'status');; ?>
	    
    <div class="form-actions">
        <button class="btn btn-success" type="submit">
            <?=$model->isNewRecord ? 'Добавить' : 'Сохранить'; ?>
        </button>
        <span class="text_button_padding">или</span>
        <?=CHtml::link('назад', array('list','Program_page'=>$_GET['Program_page'])); ?>
	</div>
<? $this->endWidget(); ?>

protected/views/site/index.php
<div class="page-header">
        <h1>jQuery File Upload Demo</h1>
    </div>
    <blockquote>
        <p>File Upload widget with multiple file selection, drag&amp;drop support, progress bars and preview images for jQuery.<br>
        Supports cross-domain, chunked and resumable file uploads and client-side image resizing.<br>
        Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.</p>
    </blockquote>
    <br>
    <?php
	$this->widget('xupload.XUpload', array(
		'url' => Yii::app()->createUrl("site/upload", array(
            "id" => (int)$model->id,
            "attribute" => "image",
            "model" => "Program",
        )),
		'model' => $model,
        'attribute' => 'image',
		'multiple' => true,
	));
	?>
		
		
    <br>
    <div class="well">
        <h3>Demo Notes</h3>
        <ul>
            <li>The maximum file size for uploads in this demo is <strong>5 MB</strong> (default file size is unlimited).</li>
            <li>Only image files (<strong>JPG, GIF, PNG</strong>) are allowed in this demo (by default there is no file type restriction).</li>
            <li>Uploaded files will be deleted automatically after <strong>5 minutes</strong> (demo setting).</li>
            <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage with Google Chrome, Mozilla Firefox and Apple Safari.</li>
            <li>Please refer to the <a href="https://github.com/blueimp/jQuery-File-Upload">project website</a> and <a href="https://github.com/blueimp/jQuery-File-Upload/wiki">documentation</a> for more information.</li>
            <li>Built with Twitter's <a href="http://twitter.github.com/bootstrap/">Bootstrap</a> toolkit and Icons from <a href="http://glyphicons.com/">Glyphicons</a>.</li>
        </ul>
    </div>